#!/bin/bash
set -euo pipefail

function errxit() {
  echo $1 > /dev/stderr
  exit $2
}

function get-docker-password() {
  CTX=`kubectl config current-context`

  case $CTX in
    juvo-ilab-prod) NS=staging-kn ;;
    juvo-dev) NS=dev-kn ;;
    *) errxit "Invalid context $CTX" 1 ;;
  esac

  kubectl get secret dockerhub -n$NS -ojsonpath='{.data.password}' |
  base64 -d
}

TAG=latest
set +u
if [ "$1" != "" ]; then
  TAG=$1
fi
set -u

get-docker-password |
docker login -u jurisfuturasb --password-stdin

for TARGET in build run; do
  ARTIFACT="jurisfutura/juvo-poetry-$TARGET:$TAG"
  docker buildx build . -t $ARTIFACT --target $TARGET
  docker push $ARTIFACT
done

cat << EOF > ./builder.toml
[build]
image = "jurisfutura/juvo-poetry-build:$TAG"

[run]
[[run.images]]
image = "jurisfutura/juvo-poetry-run:$TAG"
EOF

BUILDER_IMAGE="jurisfutura/juvo-poetry-builder:$TAG"
pack builder create $BUILDER_IMAGE --config ./builder.toml
docker push $BUILDER_IMAGE
