---
name: CI

on: push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cnb-components/buildpacks/juvo-poetry-buildpack/go.mod
      - name: Build binaries
        run: |
          for BIN in detect build; do
           go build $@ -ldflags="-s -w" -o cnb-components/buildpacks/juvo-poetry-buildpack/bin/$BIN cnb-components/buildpacks/juvo-poetry-buildpack/cmd/$BIN/main.go
           done
        env:
          GOOS: linux
