---
name: CI

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cnb-components/buildpacks/juvo-poetry-buildpack/go.mod
      - name: Run tests
        run: go test
        working-directory: ${{ github.workspace }}/cnb-components/buildpacks/juvo-poetry-buildpack/tests/juvo_test

